export const DEVICE_LOGIN_SUCCESS = "DEVICE_LOGIN_SUCCESS";
export const DEVICE_LOGIN_FAILED = "DEVICE_LOGIN_FAILED";
export const DEVICE_CONNECTION_CONFIGURED = "DEVICE_CONNECTION_CONFIGURED";
export const SET_DEVICE_CONNECTION = "SET_DEVICE_CONNECTION";
export const WEBEX_LOGIN_SUCCESS = "WEBEX_LOGIN_SUCCESS";
export const WEBEX_LOGIN_FAILED = "WEBEX_LOGIN_FAILED";
export const O365_LOGIN_SUCCESS = "O365_LOGIN_SUCCESS";
export const O365_LOGIN_FAILED = "O365_LOGIN_FAILED";
export const DEVICE_PREFS_UPDATE_SUCCESS = "DEVICE_PREFS_UPDATE_SUCCESS";
export const DEVICE_DEPLOY_PREFS_SUCCESS = "DEVICE_DEPLOY_PREFS_SUCCESS";
export const DEVICE_DEPLOY_PREFS_FAILED = "DEVICE_DEPLOY_PREFS_FAILED";
export const WEBEX_LOAD_WORKSPACES_SUCCESS = "WEBEX_LOAD_WORKSPACES_SUCCESS";
export const WEBEX_LOAD_WORKSPACES_FAILED = "WEBEX_LOAD_WORKSPACES_FAILED";
export const WEBEX_ACTIVATION_CODE_SUCCESS = "WEBEX_ACTIVATION_CODE_SUCCESS";
export const WEBEX_ACTIVATION_CODE_FAILED = "WEBEX_ACTIVATION_CODE_FAILED";
export const DEVICE_DEPLOY_ACTIVATION_CODE_SUCCESS =
  "DEVICE_DEPLOY_ACTIVATION_CODE_SUCCESS";
export const DEVICE_DEPLOY_ACTIVATION_CODE_FAILED =
  "DEVICE_DEPLOY_ACTIVATION_CODE_FAILED";
export const WEBEX_DEPLOY_POST_REGISTRATION_SETTINGS_SUCCESS =
  "WEBEX_DEPLOY_POST_REGISTRATION_SETTINGS_SUCCESS";
export const WEBEX_DEPLOY_POST_REGISTRATION_SETTINGS_FAILED =
  "WEBEX_DEPLOY_POST_REGISTRATION_SETTINGS_FAILED";
export const DEVICE_CLOSE_FIRST_TIME_WIZARD_SUCCESS =
  "DEVICE_CLOSE_FIRST_TIME_WIZARD_SUCCESS";
export const DEVICE_CLOSE_FIRST_TIME_WIZARD_FAILED =
  "DEVICE_CLOSE_FIRST_TIME_WIZARD_FAILED";
export const DEVICE_SET_DATE_TIME_PREFS_SUCCESS =
  "DEVICE_SET_DATE_TIME_PREFS_SUCCESS";
export const DEVICE_SET_DATE_TIME_PREFS_FAILED =
  "DEVICE_SET_DATE_TIME_PREFS_FAILED";
export const DEVICE_SET_LANGUAGE_SUCCESS = "DEVICE_SET_LANGUAGE_SUCCESS";
export const DEVICE_SET_LANGUAGE_FAILED = "DEVICE_SET_LANGUAGE_FAILED";
export const DEVICE_RESET_SUCCESS = "DEVICE_RESET_SUCCESS";
export const DEVICE_RESET_FAILED = "DEVICE_RESET_FAILED";

export const WEBEX_GET_DEVICES_SUCCESS = "WEBEX_GET_DEVICES_SUCCESS";
export const WEBEX_GET_DEVICES_FAILED = "WEBEX_GET_DEVICES_FAILED";
export const WEBEX_CREATE_WORKSPACE_SUCCESS = "WEBEX_CREATE_WORKSPACE_SUCCESS";
export const WEBEX_CREATE_WORKSPACE_FAILED = "WEBEX_CREATE_WORKSPACE_FAILED";

export const WEBEX_BEGIN_API_CALL = "WEBEX_BEGIN_API_CALL";
export const WEBEX_API_CALL_ERROR = "WEBEX_API_CALL_ERROR";
export const O365_BEGIN_API_CALL = "O365_BEGIN_API_CALL";
export const O365_API_CALL_ERROR = "O365_API_CALL_ERROR";
export const DEVICE_BEGIN_API_CALL = "DEVICE_BEGIN_API_CALL";
export const DEVICE_API_CALL_ERROR = "DEVICE_API_CALL_ERROR";

export const ROOMOS_BEGIN_API_CALL = "ROOMOS_BEGIN_API_CALL";
export const SWUPDATE_INFO_SUCCESS = "SWUPDATE_INFO_SUCCESS";
export const SWUPDATE_INFO_FAILED = "SWUPDATE_INFO_FAILED";
export const SET_SW_CHANNEL = "SET_SW_CHANNEL";

export const DEVICE_UPDATE_SUCCESS = "DEVICE_UPDATE_SUCCESS";
export const DEVICE_UPDATE_FAILED = "DEVICE_UPDATE_FAILED";

export const LOG_ADD = "LOG_ADD";
